### PR TITLE
Project rewrite in typescript

### PR DESCRIPTION
**Pull request by artus9033**
As this is a helpful project, I gave it a rewrite in typescript so as to support type annotations and make the code base a bit easier to be maintained. For now, a few lines that rely on Chart.js's typings are ignored with `// @ts-ignore` and these need to be overriden with `declare module` - I created an example overide for the plugin's options as well.
Compilation has not changed much, still uses rollup with typescript plugin, and emits typings to `dist` as well. Of course, all tests still pass.
Please feel free to verify whether it's okay to be merged.

### CODE REVIEW

**Comment by chrispahm** [comment]
Sorry I didn't get to review this yet, but it looks great!

**Comment by artus9033** [comment]
@chrispahm  will you review this PR for a possible merge?

**Comment by akkitheakhil** [comment]
I would really appreciate it if this PR could be reviewed and merged.

**Comment by artus9033** [comment]
@chrispahm can you report any progress regardin the review of this PR?

**Comment by chrispahm** [comment]
Hey I'm sorry for taking so long, I don't work with Chart.js anymore so this work just comes on top of the other things... If someone's interested to maintain this repo (maybe @artus9033?) please write me a short mail (see profile)! 

Note that there are still a lot of test cases missing (see #40), plus there are no unit test at all! This is the main reason why I started lagging behind all these PRs and issues, as all options need to be tested manually after each update. Maybe Github Copilot / ChatGPT could be of help writing these test but I wouldn't be too sure about it...

**Comment by artus9033** [comment]
Now resolved in #146  🎸

**Pull request closed without merging**
