### PR TITLE
Added x, y option for data points

### PR DESCRIPTION
**Pull request by thelim3y**
Hita, I added the ability to drag x, y data point objects (just y gets modified). Unsure if useful to the rest of the world but creating a PR just in case.

### CODE REVIEW

**Comment by chrispahm** [comment]
Hey, thanks a lot for the PR! Sorry I don't have much time to like at the changes right now, just wanted to ask whether you could a) add a scmall description for what it does in the README and possibly b) add a small example for gh-pages (optional though). By the way, saw that you had a couple changes in the dist directory, did you bundle them with webpack from the src files?

**Comment by thelim3y** [comment]
Hiya. Yup I'll add something to the readme, I'm also a little pushed for time so it may take me a few days. Yes, I used Webpack to bundle the files, that'll be the changes int he commit. Should I have not done that?

I've been adding a few things to the code and should probably clean it up and submit a new PR with the additions + readme update (+example if I can get to it). ttys

**Comment by chrispahm** [comment]
Sounds all good to me! 👌

**Comment by chrispahm** [comment]
Sorry for taking me so long! Thanks again for the PR!

**Pull request merged**
